version: "3"

services:
  web-erp:
    build:
      context: .
      dockerfile: Dockerfile-xampp 
    image: xampp-web-erp
    restart: always
    ports:
      - "8080:80"
      - "8081:443"
  
  # Database
  db-mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_PASSWORD: root
    # networks:
    #   - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db-mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db-mysql
      MYSQL_ROOT_PASSWORD: secret
    # networks:
    #   - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: